server:
  http_port: 10047
  port: 10048
  ssl:
    protocol: "TLS"
    key-store: "file:./keys/tomcat.p12"
    key-store-password: "162276"
    key-store-type: "PKCS12"

my:
  static-location: "C:/Code/Web/WebServerWeb"
  error-pages:
    - code: 404
      location: "/error/404.html"
    - code: 500
      location: "/error/500.html"
  tray-icon: false
  tray-icon-index: 1