server:
  http_port: 10047
  https_port: 10048
  http_to_https: false
  ssl:
    protocol: "TLS"
    key-store: "file:./keys/tomcat.p12"
    key-store-password: "162276"
    key-store-type: "PKCS12"

my:
  static-location: "C:/Code/Web/WebServerWeb"
  tray-icon: false
  tray-icon-index: 1