application:
  title: WebServer
  version: dev

server:
  port: 10048
  http2:
    enabled: true
  ssl:
    key-store: file:./keys/www.DevilSpiderX.ltd.pfx
    key-store-password: 162276
    key-store-type: PKCS12

spring:
  web:
    resources:
      static-locations:
        - file:/C:/Code/Web/WebServerWeb
  banner:
    location: classpath:banner.txt
  main:
    banner-mode: LOG

bee:
  db:
    dbName: MySQL
    driverName: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/webserver?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=Asia/Shanghai
    username: root
    password: zdy18906071630
  osql:
    showSQL: false

devilspiderx:
  v2ray:
    exe-path: C:/MyDownloads/v2ray - Server/v2ray-windows-64/v2ray.exe
    config-path: C:/MyDownloads/v2ray - Server/v2ray-windows-64/config.json