application:
  title: WebServer
  version: dev

server:
  port: 10048
  http2:
    enabled: true

spring:
  web:
    resources:
      static-locations:
        - file:./web
  banner:
    location: classpath:banner.txt
  main:
    banner-mode: LOG

devilspiderx:
  v2ray:
    exe-path: C:/Downloads/v2ray - Server/v2ray-windows-64/v2ray.exe
    config-path: C:/Downloads/v2ray - Server/v2ray-windows-64/config.json