server:
  http_port: 10047
  https_port: 10048
  http2:
    enabled: true
  ssl:
    protocol: "TLS"
    key-store: "file:./keys/Certificate.p12"
    key-store-password: "162276"
    key-store-type: "PKCS12"

bee:
  db:
    dbName: MySQL
    driverName: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/webserver?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=Asia/Shanghai
    username: root
    password: zdy18906071630
  osql:
    showSQL: false

devilspiderx:
  static-location: C:/Code/Web/WebServerWeb
  v2ray:
    exe-path: "C:/MyDownloads/v2ray - Server/v2ray-windows-64/v2ray.exe"
    config-path: "C:/MyDownloads/v2ray - Server/v2ray-windows-64/config.json"