spring:
  profiles:
    active: dev
  web:
    resources:
      static-locations:
        - file:D:/Code/Web/devilspiderx-vue/dist

server:
  port: 10048

devilspiderx:
  v2ray:
    exe-path: C:/Downloads/v2ray - Server/v2ray-windows-64/v2ray.exe
    config-path: C:/Downloads/v2ray - Server/v2ray-windows-64/config.json
  pid-file-name: devilspiderx.pid
  avatar-dir-path: target/avatarImages

mqtt:
  bemfa:
    topic: topic
    client-id: clientId
