server:
  port: 10048
  http2:
    enabled: true

spring:
  web:
    resources:
      static-locations:
        - file:./web
  banner:
    location: classpath:banner.txt
  main:
    banner-mode: LOG
  config:
    import:
      - file:user-config.yml
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB

sa-token:
  token-name: DSXSessionId
  is-concurrent: true
  is-share: false