application:
  title: Development
  version: dev

sa-token:
  is-log: true

logging:
  level:
    root: debug

bee:
  osql:
    logger-type: slf4j
    show-sql:
      show-type: true
      show-executable-sql: true

mybatis:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl