server:
  port: 80
  http2:
    enabled: true

spring:
  web:
    resources:
      static-locations:
        - file:./web
  banner:
    location: classpath:banner.txt
  main:
    banner-mode: LOG
  config:
    import:
      - file:user-config.yml
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/devilspiderx?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=Asia/Shanghai
    username: root
    password: 123456

sa-token:
  token-name: DSXSessionId
  is-concurrent: true
  is-share: false
