application:
  title: Development
  version: dev

sa-token:
  is-log: true

logging:
  level:
    root: debug

bee:
  osql:
    logger-type: slf4j
    show-s-q-l: true
    show-sql:
      show-type: true
      show-executable-sql: true